import 'dart:io';

import 'package:flutter/material.dart' show BuildContext, ScaffoldMessenger, SnackBar, SnackBarBehavior, Text;
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';

import '../../../../core/theme/app_theme.dart';
import '../../domain/entities/bill_result.dart';
import '../../domain/entities/calculated_bill.dart';
import '../../domain/entities/person_order.dart';

class ReceiptPdfGenerator {
  ReceiptPdfGenerator._();

  static final PdfColor _primary = PdfColor.fromInt(0xFFFF6B6B);
  static final PdfColor _primaryLight = PdfColor.fromInt(0xFFFFE5E5);
  static final PdfColor _textPrimary = PdfColor.fromInt(0xFF212529);
  static final PdfColor _textSecondary = PdfColor.fromInt(0xFF6C757D);
  static final PdfColor _border = PdfColor.fromInt(0xFFE9ECEF);
  static final PdfColor _background = PdfColor.fromInt(0xFFF8F9FA);

  static Future<bool> generateAndShare({
    required BuildContext context,
    required BillResult result,
    required List<PersonOrder> orders,
    String fileName = 'PatunganKuy_Receipt',
  }) async {
    try {
      final pdf = pw.Document();
      final generatedAt = DateTime.now();

      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(36),
          build: (ctx) => [
            _header(generatedAt),
            pw.SizedBox(height: 20),
            _summaryCard(result),
            pw.SizedBox(height: 20),
            pw.Text(
              'Per Person Breakdown',
              style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold, color: _textPrimary),
            ),
            pw.SizedBox(height: 8),
            ...result.calculatedBills.map((bill) {
              final order = orders.where((o) => o.id == bill.personId).toList();
              return _personSection(bill.name, order.isNotEmpty ? order.first.items : const <OrderItem>[], bill);
            }),
            pw.SizedBox(height: 24),
            pw.Center(
              child: pw.Text(
                'Generated by PatunganKuy - Patungan? Kuy!',
                style: pw.TextStyle(fontSize: 9, color: _textSecondary),
              ),
            ),
          ],
        ),
      );

      final bytes = await pdf.save();
      final tempDir = await getTemporaryDirectory();
      final filePath = '${tempDir.path}/$fileName.pdf';
      final file = File(filePath);
      await file.writeAsBytes(bytes);

      await Share.shareXFiles([XFile(filePath, mimeType: 'application/pdf')], text: 'PatunganKuy Bill Receipt');
      return true;
    } catch (e) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error exporting PDF: $e'), behavior: SnackBarBehavior.floating),
        );
      }
      return false;
    }
  }

  static pw.Widget _header(DateTime date) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      crossAxisAlignment: pw.CrossAxisAlignment.end,
      children: [
        pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text('PatunganKuy', style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold, color: _primary)),
            pw.SizedBox(height: 2),
            pw.Text('Split Bill Receipt', style: pw.TextStyle(fontSize: 11, color: _textSecondary)),
          ],
        ),
        pw.Text(_formatDate(date), style: pw.TextStyle(fontSize: 10, color: _textSecondary)),
      ],
    );
  }

  static pw.Widget _summaryCard(BillResult result) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        color: _background,
        borderRadius: pw.BorderRadius.circular(10),
        border: pw.Border.all(color: _border),
      ),
      child: pw.Column(
        children: [
          _row('Total Base', result.totalBase),
          _row('Total Fees', result.totalFees),
          _row('Total Discount', -result.totalDiscount),
          pw.Padding(
            padding: const pw.EdgeInsets.symmetric(vertical: 8),
            child: pw.Divider(color: _border, height: 1),
          ),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text('Grand Total', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold, color: _textPrimary)),
              pw.Text(
                AppTheme.formatRupiah(result.grandTotal),
                style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold, color: _primary),
              ),
            ],
          ),
        ],
      ),
    );
  }

  static pw.Widget _personSection(String name, List<OrderItem> items, CalculatedBill bill) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 10),
      padding: const pw.EdgeInsets.all(14),
      decoration: pw.BoxDecoration(
        borderRadius: pw.BorderRadius.circular(10),
        border: pw.Border.all(color: _border),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(name, style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold, color: _textPrimary)),
              pw.Container(
                padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 3),
                decoration: pw.BoxDecoration(color: _primaryLight, borderRadius: pw.BorderRadius.circular(999)),
                child: pw.Text(
                  AppTheme.formatRupiah(bill.finalPayable),
                  style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold, color: _primary),
                ),
              ),
            ],
          ),
          if (items.isNotEmpty) ...[
            pw.SizedBox(height: 8),
            ...items.map(
              (item) => pw.Padding(
                padding: const pw.EdgeInsets.only(bottom: 2),
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text(item.name.isEmpty ? 'Item' : item.name, style: pw.TextStyle(fontSize: 10, color: _textPrimary)),
                    pw.Text(AppTheme.formatRupiah(item.price), style: pw.TextStyle(fontSize: 10, color: _textPrimary)),
                  ],
                ),
              ),
            ),
          ],
          pw.SizedBox(height: 6),
          pw.Text(
            'Base: ${AppTheme.formatRupiah(bill.originalPrice)}   '
            '+ Fee: ${AppTheme.formatRupiah(bill.proportionalFee)}   '
            '- Disc: ${AppTheme.formatRupiah(bill.proportionalDiscount)}',
            style: pw.TextStyle(fontSize: 9, color: _textSecondary),
          ),
        ],
      ),
    );
  }

  static pw.Widget _row(String label, double value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 2),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(label, style: pw.TextStyle(fontSize: 11, color: _textSecondary)),
          pw.Text(AppTheme.formatRupiah(value), style: pw.TextStyle(fontSize: 11, color: _textPrimary)),
        ],
      ),
    );
  }

  static String _formatDate(DateTime d) {
    const m = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    return '${d.day} ${m[d.month - 1]} ${d.year}  ${d.hour.toString().padLeft(2, '0')}:${d.minute.toString().padLeft(2, '0')}';
  }
}
